export const books = [
  // {
  //   name: "Men are fror mars, women are from venue",
  //   stall_price: 149,
  //   pre_booking_price: 135,
  //   img: "https://drive.google.com/file/d/1qZf2OGSIRwQ9NOi73KfDjJjm2_3VcoxG/view?usp=drive_link",
  // },
  {
    name: "The Girl on the Train",
    stall_price: 249,
    pre_booking_price: 225,
    img: "assets/the_girl_on_the_train.jpg",
  },
  {
    name: "1984 by George",
    stall_price: 129,
    pre_booking_price: 117,
    img: "assets/1984.jpg",
  },
  {
    name: "The vinci code",
    stall_price: 259,
    pre_booking_price: 234,
    img: "assets/code.jpg",
  },
  // {
  //   name: "Ikigai hard cover book",
  //   stall_price: 199,
  //   pre_booking_price: 180,
  //   img: "https://drive.google.com/file/d/1kYbsoHNuca48JiOeNlFuZRpusNvvK2dB/view?usp=drive_link",
  // },
  {
    name: "Death",
    stall_price: 249,
    pre_booking_price: 225,
    img: "assets/death.jpg",
  },
  // {
  //   name: "Cosmos",
  //   stall_price: 149,
  //   pre_booking_price: 135,
  //   img: "https://drive.google.com/file/d/1qPqpAK_VHQwC1z1EiCiKNlVayNCt-7jU/view?usp=drive_link",
  // },
  {
    name: "Elon musk",
    stall_price: 129,
    pre_booking_price: 117,
    img: "assets/elon_musk.jpg",
  },
  {
    name: "Ignited minds",
    stall_price: 129,
    pre_booking_price: 117,
    img: "assets/minds.jpg",
  },
  {
    name: "White nights",
    stall_price: 99,
    pre_booking_price: 90,
    img: "assets/white_nights.jpg",
  },
  {
    name: "How to talk to anyone",
    stall_price: 175,
    pre_booking_price: 158,
    img: "assets/talk_anyone.jpg",
  },
  {
    name: "48 laws of power",
    stall_price: 199,
    pre_booking_price: 180,
    img: "assets/power.jpg",
  },
  {
    name: "Ugly Love",
    stall_price: 129,
    pre_booking_price: 117,
    img: "assets/ugly_love.jpg",
  },
  {
    name: "Crime and Punishment",
    stall_price: 225,
    pre_booking_price: 203,
    img: "assets/crime_punishment.jpg",
  },
  // {
  //   name: "I fell in love with hope",
  //   stall_price: 199,
  //   pre_booking_price: 180,
  //   img: "https://drive.google.com/file/d/1ns0uTqplgPljCL2c6bP15lPPasKhefa8/view?usp=drive_link",
  // },
  {
    name: "Limitless",
    stall_price: 149,
    pre_booking_price: 135,
    img: "assets/limitless.jpg",
  },
  {
    name: "Can't hurt me",
    stall_price: 199,
    pre_booking_price: 180,
    img: "assets/can_hurt_me.jpg",
  },
  // {
  //   name: "To kill a mockingbird",
  //   stall_price: 199,
  //   pre_booking_price: 180,
  //   img: "https://drive.google.com/file/d/1qNMgCChwj3HOC2ZPDVrY8ljHiGbS_eiq/view?usp=drive_link",
  // },
  // {
  //   name: "Manto ki anmol kahaniya",
  //   stall_price: 199,
  //   pre_booking_price: 180,
  //   img: "https://drive.google.com/file/d/1jB3DDAZtWGfQ305bTRS-O6t2qJgSMk1x/view?usp=drive_link",
  // },
  // {
  //   name: "Verity",
  //   stall_price: 199,
  //   pre_booking_price: 180,
  //   img: "https://drive.google.com/file/d/1j7G4y4kZjueEuWjF1nW4wt0RqvRqk8kk/view?usp=drive_link",
  // },
  // {
  //   name: "Never finished",
  //   stall_price: 249,
  //   pre_booking_price: 225,
  //   img: "https://drive.google.com/file/d/1rcGdX5wbIKHYwZxnqouLIcUrKloSss6k/view?usp=drive_link",
  // },
  // {
  //   name: "It starts with us",
  //   stall_price: 149,
  //   pre_booking_price: 135,
  //   img: "assets/it_starts_with_us.jpg",
  // },
  {
    name: "It ends with us",
    stall_price: 149,
    pre_booking_price: 135,
    img: "assets/it_ends_with_us.jpg",
  },
  // {
  //   name: "Godan",
  //   stall_price: 179,
  //   pre_booking_price: 162,
  //   img: "https://drive.google.com/file/d/1iyVs71rsFd5d5G9-Mzt2Fa3DmZDRmmlY/view?usp=drive_link",
  // },
  // {
  //   name: "Silent Patient",
  //   stall_price: 175,
  //   pre_booking_price: 158,
  //   img: "https://drive.google.com/file/d/1j14QfjLyQE3IPjz3lzapRIcu-xxF1Qvz/view?usp=drive_link",
  // },
  // {
  //   name: "Zero to one",
  //   stall_price: 149,
  //   pre_booking_price: 135,
  //   img: "https://drive.google.com/file/d/1j15V7s4XN7vcJouR9P_f8V3x3LSOTcfJ/view?usp=drive_link",
  // },
  // {
  //   name: "Everything is psychology",
  //   stall_price: 149,
  //   pre_booking_price: 135,
  //   img: "https://drive.google.com/file/d/1j4zF-gnyPMevDUW2gZsCmPOSYlyu8iEn/view?usp=drive_link",
  // },
  // {
  //   name: "The power of habits",
  //   stall_price: 199,
  //   pre_booking_price: 180,
  //   img: "https://drive.google.com/file/d/1rBMO-5bx_IJd3VSegz38YK9utjAoLi9w/view?usp=drive_link",
  // },
  // {
  //   name: "12 rules for life",
  //   stall_price: 199,
  //   pre_booking_price: 180,
  //   img: "https://drive.google.com/file/d/1l-F7L5qhzLVZwMSyk_Cf5iuHVX3lQsx3/view?usp=drive_link",
  // },
  // {
  //   name: "The theory of everything",
  //   stall_price: 149,
  //   pre_booking_price: 135,
  //   img: "https://drive.google.com/file/d/1kzAdRUOWjgdjk7mK8sLvY4kifKo1LFPg/view?usp=drive_link",
  // },
  // {
  //   name: "The miracle morning",
  //   stall_price: 149,
  //   pre_booking_price: 135,
  //   img: "https://drive.google.com/file/d/1r2RgY0auV9gxhbgk5X78HewY-HQeMC8Y/view?usp=drive_link",
  // },
  // {
  //   name: "Don't believe everything you think",
  //   stall_price: 129,
  //   pre_booking_price: 117,
  //   img: "https://drive.google.com/file/d/1ksGtmoqFakX0CX3NsEHgvLbHgAYLtkTe/view?usp=drive_link",
  // },
  // {
  //   name: "The subtle art of not giving a f*ck",
  //   stall_price: 119,
  //   pre_booking_price: 108,
  //   img: "https://drive.google.com/file/d/1ksGtmoqFakX0CX3NsEHgvLbHgAYLtkTe/view?usp=drive_link",
  // },
  // {
  //   name: "Aghori",
  //   stall_price: 149,
  //   pre_booking_price: 135,
  //   img: "https://drive.google.com/file/d/1klpPOQZuBPv3T1HiZeFwFWwkYKuCtcdK/view?usp=drive_link",
  // },
  // {
  //   name: "Power of subconscious mind",
  //   stall_price: 149,
  //   pre_booking_price: 135,
  //   img: "https://drive.google.com/file/d/1khy-68kafaPsITUbcczVT0KyqINz7bnW/view?usp=drive_link",
  // },
  {
    name: "Ikigai",
    stall_price: 129,
    pre_booking_price: 117,
    img: "assets/ikigai.jpg",
  },
  // {
  //   name: "Brida",
  //   stall_price: 199,
  //   pre_booking_price: 180,
  //   img: "https://drive.google.com/file/d/1qZf2OGSIRwQ9NOi73KfDjJjm2_3VcoxG/view?usp=drive_link",
  // },
  // {
  //   name: "Attitude is everything",
  //   stall_price: 99,
  //   pre_booking_price: 90,
  //   img: "https://drive.google.com/file/d/1l2DfGB876Ii46QpGlPK-Dk10QegjUFKs/view?usp=drive_link",
  // },
  // {
  //   name: "Tales of Shakespeare",
  //   stall_price: 99,
  //   pre_booking_price: 90,
  //   img: "https://drive.google.com/file/d/1lE8L8DVzKi_Y1Upl7TB4hOqmXOlFaLGM/view?usp=drive_link",
  // },
  {
    name: "The sign of the four - A sherlock holmes Adventure",
    stall_price: 79,
    pre_booking_price: 72,
    img: "assets/four.jpg",
  },
  // {
  //   name: "The lord of the rings",
  //   stall_price: 149,
  //   pre_booking_price: 135,
  //   img: "https://drive.google.com/file/d/1kFoEIYgUovSSqCg_KnM-nprv54Nn6eG4/view?usp=drive_link",
  // },
  // {
  //   name: "Gulliver travels",
  //   stall_price: 99,
  //   pre_booking_price: 90,
  //   img: "https://drive.google.com/file/d/1qT4Sp0Y9I_XkQ0zIHrGTBXqXgQBgCvQ-/view?usp=drive_link",
  // },
  {
    name: "Good Vibes good life",
    stall_price: 119,
    pre_booking_price: 108,
    img: "assets/good_vibes_good_life.jpg",
  },
  {
    name: "Chronicle of a Death Foretold",
    stall_price: 99,
    pre_booking_price: 90,
    img: "assets/chronicle_of_death.jpg",
  },
  // {
  //   name: "Ego is the enemy",
  //   stall_price: 149,
  //   pre_booking_price: 135,
  //   img: "https://drive.google.com/file/d/1kTdgcnGeafFkzLY_G-iv77rdt7ZLHiMW/view?usp=drive_link",
  // },
  {
    name: "Man's search for meaning",
    stall_price: 79,
    pre_booking_price: 72,
    img: "assets/man_search.jpg",
  },
  {
    name: "The Alchemist",
    stall_price: 109,
    pre_booking_price: 99,
    img: "assets/alchemist.jpg",
  },
  // {
  //   name: "Secrets of the millionaire mind",
  //   stall_price: 100,
  //   pre_booking_price: 90,
  //   img: "https://drive.google.com/file/d/1l7XFd2JQlkBkxc2TsUJXDVRijf0rHS-G/view?usp=drive_link",
  // },
  // {
  //   name: "Gorky Park",
  //   stall_price: 75,
  //   pre_booking_price: 68,
  //   img: "https://drive.google.com/file/d/1qZHHXlTD3hE_xOUsEHPmHpm_qE_rlOhS/view?usp=drive_link",
  // },
  // {
  //   name: "The compound effect",
  //   stall_price: 109,
  //   pre_booking_price: 99,
  //   img: "https://drive.google.com/file/d/1qT4Sp0Y9I_XkQ0zIHrGTBXqXgQBgCvQ-/view?usp=drive_link",
  // },
  // {
  //   name: "The adventures of Sherlock Holmes",
  //   stall_price: 99,
  //   pre_booking_price: 90,
  //   img: "https://drive.google.com/file/d/1qYsBI7uetto8BMJoieJ4OuuLrKEOF93U/view?usp=drive_link",
  // },
  {
    name: "Do it today",
    stall_price: 79,
    pre_booking_price: 72,
    img: "assets/do_it_today.jpg",
  },
  // {
  //   name: "Look back in anger",
  //   stall_price: 79,
  //   pre_booking_price: 72,
  //   img: "https://drive.google.com/file/d/1pjkbr9aifQZ4u3DDbJ0-ZTYoDavsaM13/view?usp=drive_link",
  // },
  // {
  //   name: "Holes",
  //   stall_price: 129,
  //   pre_booking_price: 117,
  //   img: "https://drive.google.com/file/d/1pndbrCYT4d1Rztz0JqBwFQDblkTHQdDX/view?usp=drive_link",
  // },
  // {
  //   name: "Frankenstein",
  //   stall_price: 99,
  //   pre_booking_price: 90,
  //   img: "https://drive.google.com/file/d/1k0OJDCzv3LPIWhnkNaLRC0x7WXQtefpf/view?usp=drive_link",
  // },
  {
    name: "Heart of darkness",
    stall_price: 99,
    pre_booking_price: 90,
    img: "assets/heart_of_darkness.jpg",
  },
  {
    name: "I don't love you anymore",
    stall_price: 119,
    pre_booking_price: 108,
    img: "assets/love.jpg",
  },
  // {
  //   name: "Karma - sadhguru",
  //   stall_price: 199,
  //   pre_booking_price: 180,
  //   img: "https://drive.google.com/file/d/1rIBSJiiRKF4UhOA_NbsAzOyrfX58nj3P/view?usp=drive_link",
  // },
  // {
  //   name: "Lucifer was innocent",
  //   stall_price: 99,
  //   pre_booking_price: 90,
  //   img: "https://drive.google.com/file/d/1mWzMWYV0IkO47Rl2rWyCNPzW1QdM7Ukn/view?usp=drive_link",
  // },
  // {
  //   name: "The 10X rule",
  //   stall_price: 109,
  //   pre_booking_price: 99,
  //   img: "https://drive.google.com/file/d/1mQX1BChEdATrcPfsXsamDTs86LRWteex/view?usp=drive_link",
  // },
  // {
  //   name: "The parasytic mind",
  //   stall_price: 149,
  //   pre_booking_price: 135,
  //   img: "https://drive.google.com/file/d/1mcWByvMFzMZej7oiSpa9SegreAw_gZ0m/view?usp=drive_link",
  // },
  // {
  //   name: "Hyper focus",
  //   stall_price: 199,
  //   pre_booking_price: 180,
  //   img: "https://drive.google.com/file/d/1mOKwpHkDPFY3ruawSNPHnxB5Y_K5t0Df/view?usp=drive_link",
  // },
  // {
  //   name: "The god of small things",
  //   stall_price: 199,
  //   pre_booking_price: 180,
  //   img: "https://drive.google.com/file/d/1mdNTP9Qu-Dql6eL7e97u6QO2iFXp_-zK/view?usp=drive_link",
  // },
  // {
  //   name: "Dopamine nation",
  //   stall_price: 129,
  //   pre_booking_price: 117,
  //   img: "https://drive.google.com/file/d/1mL3RNt4MzcyfHj_mfGNxbnSteoCcLU_C/view?usp=drive_link",
  // },
  // {
  //   name: "Psychology of money",
  //   stall_price: 119,
  //   pre_booking_price: 108,
  //   img: "https://drive.google.com/file/d/1mAamDslONetQM5pHnt2DXryIu3lHbiqH/view?usp=drive_link",
  // },
  // {
  //   name: "How to win and influence people",
  //   stall_price: 119,
  //   pre_booking_price: 108,
  //   img: "https://drive.google.com/file/d/1mL19hqf8xv7TPPOPt382v-uikp6Du1C4/view?usp=drive_link",
  // },
  // {
  //   name: "You only live once",
  //   stall_price: 149,
  //   pre_booking_price: 135,
  //   img: "https://drive.google.com/file/d/1mugoCsLDTK__NseO-ZKl5aCXn4f_4ImG/view?usp=drive_link",
  // },
  // {
  //   name: "7 habits of highly effective people",
  //   stall_price: 149,
  //   pre_booking_price: 135,
  //   img: "https://drive.google.com/file/d/1vDv4YjyEZoNc5GpYI11YKl74gqxs6qq9/view?usp=drive_link",
  // },
  // {
  //   name: "The 80/20 principle",
  //   stall_price: 119,
  //   pre_booking_price: 108,
  //   img: "https://drive.google.com/file/d/1rZJFqWoGdPenRBxz3YMzESkbQtlUgK1i/view?usp=drive_link",
  // },
  // {
  //   name: "Warmth",
  //   stall_price: 129,
  //   pre_booking_price: 117,
  //   img: "https://drive.google.com/file/d/1q6AhdgzSbr5PXUtVBIjyv4ljxSFssNdR/view?usp=drive_link",
  // },
  {
    name: "Think and grow rich",
    stall_price: 129,
    pre_booking_price: 117,
    img: "assets/think_and_grow.jpg",
  },
  // {
  //   name: "Pride and prejudice",
  //   stall_price: 199,
  //   pre_booking_price: 180,
  //   img: "https://drive.google.com/file/d/1rScKsXcDlPZw4bTO0zRSmrebRO13cOj4/view?usp=drive_link",
  // },
  // {
  //   name: "The study in scarlet",
  //   stall_price: 119,
  //   pre_booking_price: 108,
  //   img: "https://drive.google.com/file/d/1pQjN2eC5tYhU7pe86dDqhKRh4zIOlbVY/view?usp=drive_link",
  // },
  {
    name: "The mountain is you",
    stall_price: 149,
    pre_booking_price: 135,
    img: "assets/mountain.jpg",
  },
  // {
  //   name: "A man called ove",
  //   stall_price: 149,
  //   pre_booking_price: 135,
  //   img: "https://drive.google.com/file/d/1r0cpjNZDWspr9zTJD2x2r-21lA5so51Y/view?usp=drive_link",
  // },
  // {
  //   name: "Chetan. Bhagat - 400 days",
  //   stall_price: 119,
  //   pre_booking_price: 108,
  //   img: "https://drive.google.com/file/d/1rFOqSZU2xyqeA8kyvoIK1raw6apL7LGQ/view?usp=drive_link",
  // },
  // {
  //   name: "The secret",
  //   stall_price: 125,
  //   pre_booking_price: 113,
  //   img: "https://drive.google.com/file/d/1lizNlF6Dmtux37vbgd4CxF6kmcT9SDD4/view?usp=drive_link",
  // },
  // {
  //   name: "The diary of a ceo",
  //   stall_price: 129,
  //   pre_booking_price: 117,
  //   img: "https://drive.google.com/file/d/1lhOaXHMxzkRSDv_TULRUep3CqVF_moWB/view?usp=drive_link",
  // },
  // {
  //   name: "The guest list",
  //   stall_price: 200,
  //   pre_booking_price: 180,
  //   img: "https://drive.google.com/file/d/1lWgOLhfgSkyKboxaINqiB-52uNVpLzrY/view?usp=drive_link",
  // },
  // {
  //   name: "The murder of roger ackroyd",
  //   stall_price: 249,
  //   pre_booking_price: 225,
  //   img: "https://drive.google.com/file/d/1lFqwLiv6q1KEcVUnJO50knnAIjBo2m1t/view?usp=drive_link",
  // },
  // {
  //   name: "The housemaid",
  //   stall_price: 149,
  //   pre_booking_price: 135,
  //   img: "https://drive.google.com/file/d/1lW0zhd5--sZUMPXzJOFjzazo3fvB-kQL/view?usp=drive_link",
  // },
  // {
  //   name: "Dark matter",
  //   stall_price: 210,
  //   pre_booking_price: 189,
  //   img: "https://drive.google.com/file/d/1lG-RHkgeJV_TB7xKkWOZmzl8NJH0JYya/view?usp=drive_link",
  // },
  // {
  //   name: "Surrounded by idiots",
  //   stall_price: 199,
  //   pre_booking_price: 180,
  //   img: "https://drive.google.com/file/d/1lTEOimhCkDnd212AfbjkTH7V4EnIYZtY/view?usp=drive_link",
  // },
  // {
  //   name: "Show your work",
  //   stall_price: 179,
  //   pre_booking_price: 162,
  //   img: "https://drive.google.com/file/d/1lGWG-d473i-jtjGkqhgT6qTpnWndY1DY/view?usp=drive_link",
  // },
  {
    name: "On canaan's side",
    stall_price: 333,
    pre_booking_price: 300,
    img: "assets/side.jpg",
  },
  {
    name: "The richest man in babylon",
    stall_price: 79,
    pre_booking_price: 72,
    img: "assets/richest.jpg",
  },
  {
    name: "Nights of rain and stars",
    stall_price: 333,
    pre_booking_price: 300,
    img: "assets/rain_and_stars.jpg",
  },
  {
    name: "San Andreas",
    stall_price: 100,
    pre_booking_price: 90,
    img: "assets/san_andreas.jpg",
  },
  {
    name: "Flood Tide",
    stall_price: 333,
    pre_booking_price: 300,
    img: "assets/tide.jpg",
  },
  {
    name: "Don't blink",
    stall_price: 333,
    pre_booking_price: 300,
    img: "assets/blink.jpg",
  },
  // {
  //   name: "No more dying then",
  //   stall_price: 333,
  //   pre_booking_price: 300,
  //   img: "https://drive.google.com/file/d/1p7eeqv2yCdmoULbgeb-Wc_K6cTB70wHT/view?usp=drive_link",
  // },
  // {
  //   name: "Service of all dead",
  //   stall_price: 333,
  //   pre_booking_price: 300,
  //   img: "https://drive.google.com/file/d/1p_J_F0MzEcbOTr451kdu_br_9iRwKyqQ/view?usp=drive_link",
  // },
  // {
  //   name: "Cradle of thorns",
  //   stall_price: 333,
  //   pre_booking_price: 300,
  //   img: "https://drive.google.com/file/d/1rN-RXwvT59H2juOaclr9N3G3_FuPcGAJ/view?usp=drive_link",
  // },
  // {
  //   name: "The individual society - Pearson",
  //   stall_price: 119,
  //   pre_booking_price: 108,
  //   img: "https://drive.google.com/file/d/1qRPAdNLULGf9G0nIuJTIWDKMoqYaTCoh/view?usp=drive_link",
  // },
  // {
  //   name: "Reading Gandhi",
  //   stall_price: 249,
  //   pre_booking_price: 225,
  //   img: "https://drive.google.com/file/d/1qNMgCChwj3HOC2ZPDVrY8ljHiGbS_eiq/view?usp=drive_link",
  // },
  // {
  //   name: "Concise gk manual 2025 - Pearson",
  //   stall_price: 149,
  //   pre_booking_price: 135,
  //   img: "https://drive.google.com/file/d/1q6AhdgzSbr5PXUtVBIjyv4ljxSFssNdR/view?usp=drive_link",
  // },
  // {
  //   name: "Harry Potter and the Philosopher's stone",
  //   stall_price: 199,
  //   pre_booking_price: 180,
  //   img: "https://drive.google.com/file/d/1pwl0tkfWsk4S2k9W48lXFYFOLVr1cAku/view?usp=drive_link",
  // },
  // {
  //   name: "Harry Potter and the chamber of Secrets",
  //   stall_price: 199,
  //   pre_booking_price: 180,
  //   img: "https://drive.google.com/file/d/1q48ioPHYM2M1MTOX-F67qAKPvVYbWB07/view?usp=drive_link",
  // },
  // {
  //   name: "Harry Potter and the Prisoner of azkaban",
  //   stall_price: 199,
  //   pre_booking_price: 180,
  //   img: "https://drive.google.com/file/d/1pvBU1MY1vX7kxNOkR5FvJCftQohW54PA/view?usp=drive_link",
  // },
  // {
  //   name: "Social Intelligence",
  //   stall_price: 299,
  //   pre_booking_price: 270,
  //   img: "https://drive.google.com/file/d/1qtmzMKTHRUnNqz8fPVv2U3cH6EY7V2b2/view?usp=drive_link",
  // },
];
